### PR TITLE
Support for mongoose 3.8

### PR DESCRIPTION
**Pull request by sharathciddu**
Replaced .execFind calls with .exec calls to work with mongoose 3.8.x

### CODE REVIEW

**Comment by d1b1** [comment]
Did this get pushed to NPM? I am not seeing the .exec() work for Mongoose 3.8.x?

**Comment by sharathciddu** [comment]
No. This is not pushed to npm. You could install it using the following entry in your package.json

   "mongoose-redis-cache": "git+https://github.com/baarzo/mongoose-redis-cache#813227ee647eaf9f0f260fdcc13966c3a091eb30",

**Comment by pwmckenna** [comment]
are there plans to push this to npm? is there a reason that its not?

**Comment by lbeschastny** [comment]
@sharathciddu It's a very strange way to merge. Why squashing all my commits?

It took me some time to realize that all my pull-requests are merged.

**Comment by sharathciddu** [comment]
I did not squash any of your commits. I have only submitted a pull request.
Whoever did the merge should have more details

**Comment by lbeschastny** [comment]
@sharathciddu I meant your merge [813227e](https://github.com/baarzo/mongoose-redis-cache/commit/813227ee647eaf9f0f260fdcc13966c3a091eb30). You included it in your pull request.

**Pull request merged**
